name: Test composite action "JSON Feed to Mastodon"
on:
  workflow_dispatch:

jobs:
  Mastodon:
    runs-on: ubuntu-latest

    steps:
      - name: JSON Feed to Mastodon
        uses: nhoizey/github-action-jsonfeed-to-mastodon@v1
        with:
          feedUrl: "https://nicolas-hoizey.photo/feeds/mastodon/photos.json"
